name: Automation 
on: 
  push:
    branches:
    - production
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs: 
    
  build:
    name: test
    runs-on: ubuntu-22.04
    steps: 
    - name: Github
      uses: actions/checkout@v4
    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.19.1"

    - name: Instalacja dependencji 
      run: npm install
    - name: Uruchomienie testów
      run: npm test

  deploy:
    name: deploy
    runs-on: ubutn-latest
    steps: 
    - name: Github
      uses: actions/checkout@v4
    - name: FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 20.215.225.197
        username: ${{secrets.username}}
        password: ${{secrets.password}}
        server-dir: www/


  
      


